---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    
    - name: "task1"
      ansible.builtin.command:
        cmd: "fsck -N /dev/sda"
      register: cmd1

    - debug:
        var: cmd1

