---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    
    - name: Attach the file to a loop device
      command: losetup /dev/loop3 /tmp/test_file
      register: loop_device

    - name: Verify the filesystem type
      command: blkid /dev/loop3
      register: blkid_output

    - name: Ensure filesystem is ext3
      assert:
        that:
          - "'TYPE=\"ext3\"' in blkid_output.stdout"

    - name: Detach the loop device
      command: losetup -d /dev/loop3
      ignore_errors: yes
